### ISSUE TITLE
This doesn't appear to be on crates.io

### ISSUE THREAD

**Issue by yatesco** [plausiblelabs/lens-rs#5]
`README` states to add:

```
[dependencies]
pl-lens = "1.0"
```

but https://crates.io has no `pl-lens` (or `lens-rs` for that matter ;-)).

Help :-)

**Comment by chrispcampbell** [comment]
Sorry for the delay!  I was just about to publish it in December and then realized I should simplify the way the subcrates were structured before publishing, but never got around to it until now.  I fixed things up in #6 and published today, so it's now available on crates.io, and the instructions are now accurate.

**Comment by yatesco** [comment]
Thanks!
